apiVersion: v1
kind: Service
metadata:
  name: ro-ai-admin-api
  namespace: ro-ai-intelligence
  labels:
    app.kubernetes.io/name: ro-ai-admin-api
    app.kubernetes.io/part-of: ro-ai-intelligence
spec:
  selector:
    app.kubernetes.io/name: ro-ai-admin-api
  ports:
    - name: http
      port: 8080
      targetPort: http
