apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ro-ai-world-db
  namespace: ro-ai-world
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: replace-me-region
    objects: |
      - objectName: "replace-me-world-db-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "host"
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
          - path: "database"
            objectAlias: "database"
