apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ro-ai-bot-runtime-secrets
  namespace: ro-ai-bots
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: replace-me-region
    objects: |
      - objectName: "replace-me-bot-runtime-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "account_username"
            objectAlias: "account_username"
          - path: "account_password"
            objectAlias: "account_password"
          - path: "control_token"
            objectAlias: "control_token"
