apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ro-ai-intelligence-secrets
  namespace: ro-ai-intelligence
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: replace-me-region
    objects: |
      - objectName: "replace-me-intelligence-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "model_api_key"
            objectAlias: "model_api_key"
          - path: "model_base_url"
            objectAlias: "model_base_url"
          - path: "bot_memory_table"
            objectAlias: "bot_memory_table"
