apiVersion: v1
kind: Service
metadata:
  name: rathena-char
  namespace: ro-ai-world
  labels:
    app.kubernetes.io/name: rathena-char
    app.kubernetes.io/part-of: ro-ai-world
spec:
  selector:
    app.kubernetes.io/name: rathena-char
  ports:
    - name: char
      port: 6121
      targetPort: char
